# Generated by Django 5.0.3 on 2024-03-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userdetails',
        ),
    ]
