# Generated by Django 5.0.3 on 2024-03-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0002_rename_user_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('email', models.EmailField(max_length=50)),
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursecategory', models.CharField(max_length=100)),
                ('coursenmame', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.FileField(upload_to='')),
                ('fees', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='dp',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
