# Generated by Django 5.0.3 on 2024-03-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0009_alter_userdetails_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='dp',
            field=models.ImageField(default='../media/user_images/blank-profile-picture-973460_1280.png', null=True, upload_to='../media/user_images'),
        ),
    ]
