# Generated by Django 5.0.3 on 2024-03-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0011_alter_userdetails_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='dp',
        ),
    ]
