# Generated by Django 5.0.3 on 2024-03-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0012_remove_userdetails_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='dp',
            field=models.FileField(default='1', upload_to=''),
        ),
    ]
