# Generated by Django 5.0.3 on 2024-03-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0013_userdetails_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='dp1',
            field=models.IntegerField(default=1),
        ),
    ]
