# Generated by Django 5.0.3 on 2024-03-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0014_userdetails_dp1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='dp1',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='dp',
            field=models.IntegerField(default=1),
        ),
    ]
