# Generated by Django 5.0.3 on 2024-03-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0015_remove_userdetails_dp1_alter_userdetails_dp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='dp',
            new_name='profile',
        ),
    ]
