# Generated by Django 5.0.3 on 2024-03-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0018_rename_profilepoc_userdetails_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profilepic',
            field=models.ImageField(default='../media/user_images/blank-profile-picture-973460_1280.png', upload_to='../media/user_images'),
        ),
    ]
