# Generated by Django 5.0.3 on 2024-03-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0019_alter_userdetails_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetails',
            old_name='coursenmame',
            new_name='coursename',
        ),
    ]
