# Generated by Django 5.0.3 on 2024-03-24 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0020_rename_coursenmame_coursedetails_coursename'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
