# Generated by Django 5.0.3 on 2024-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0021_coursedetails_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursecontent',
            fields=[
                ('email', models.EmailField(max_length=50)),
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='../media/videos')),
                ('notes', models.FileField(blank=True, upload_to='../media/notes')),
            ],
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='thumbnail',
            field=models.FileField(upload_to='../media/thumbnails'),
        ),
    ]
