# Generated by Django 5.0.3 on 2024-03-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0022_coursecontent_alter_coursedetails_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='thumbnail',
            field=models.FileField(upload_to=''),
        ),
    ]
