# Generated by Django 5.0.3 on 2024-03-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0023_alter_coursedetails_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='notes',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
