# Generated by Django 5.0.3 on 2024-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0024_alter_coursecontent_notes_alter_coursecontent_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='courseid',
            field=models.IntegerField(),
        ),
    ]
