# Generated by Django 5.0.3 on 2024-03-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0025_coursecontent_id_alter_coursecontent_courseid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mylearnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermail', models.EmailField(max_length=50)),
                ('courseid', models.IntegerField()),
            ],
        ),
    ]
