# Generated by Django 5.0.3 on 2024-03-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0026_mylearnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='notestitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='videotitle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
