# Generated by Django 5.0.3 on 2024-03-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0028_alter_userdetails_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermail', models.EmailField(max_length=50)),
                ('courseid', models.IntegerField(unique=True)),
            ],
        ),
    ]
