# Generated by Django 5.0.3 on 2024-03-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0029_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fees',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
