# Generated by Django 5.0.3 on 2024-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0031_whishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('ratingvalue', models.PositiveSmallIntegerField()),
                ('feedback', models.CharField(max_length=400)),
            ],
        ),
    ]
