# Generated by Django 5.0.3 on 2024-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0032_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='feedback',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
