# Generated by Django 5.0.3 on 2024-04-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0034_coursecontent_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='rating',
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
