# Generated by Django 5.0.3 on 2024-04-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0035_remove_coursecontent_rating_coursedetails_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
