# Generated by Django 5.0.3 on 2024-04-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0037_alter_cart_courseid_alter_whishlist_courseid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(max_length=100)),
                ('teachermail', models.EmailField(max_length=100)),
                ('amountpaid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('courseid', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
