# Generated by Django 5.0.3 on 2024-04-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0038_orders_alter_coursedetails_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='coursename',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='teachername',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='username',
            field=models.CharField(default=33, max_length=100),
            preserve_default=False,
        ),
    ]
