# Generated by Django 5.0.3 on 2024-04-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0039_orders_coursename_orders_teachername_orders_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='teachername',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
    ]
