# Generated by Django 5.0.3 on 2024-04-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0041_coursedetails_teachername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deletedcoursr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
            ],
        ),
    ]
