# Generated by Django 5.0.3 on 2024-04-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classroomapp', '0042_deletedcoursr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deletedcoursr',
            new_name='Deletedcourse',
        ),
    ]
